tasks:
  - init: composer install
    command: cp .env.gitpod .env
    command: php artisan key:generate --force
    command: php artisan migrate --seed --force
    command: php artisan storage:link
    command: php artisan serve --port=3000
image:
  file: .gitpod.Dockerfile
